#!/bin/sh

export CB_SERVER_PORT=8080
export CB_REMEMBER_ME_KEY=0f8fb167-6ff5-4dc4-9b42-6fb046aebd28
export CB_LOCALE=sk
export CB_BASE_URL=http://localhost:8080
export CB_DATASOURCE_CONNECTION_TIMEOUT=20000
export CB_DATASOURCE_MAXIMUM_POOL_SIZE=5
export CB_DATASOURCE=jdbc:postgresql://localhost:5433/recipes
export CB_DATASOURCE_USER=user
export CB_DATASOURCE_PASS=User123
export CB_JPA_SHOW_SQL=true
export CB_JPA_FORMAT_SQL=true
export CB_JPA_ENABLE_LAZY_LOAD_NO_TRANS=true
export CB_JPA_ENTITY_COPY_OBSERVER=allow
export CB_JPA_NON_CONTEXTUAL_CREATION=true
export CB_FLYWAY_CHECK_LOCATION=true
export CB_THYMELEAF_CACHE=true
export CB_SERVLET_MULTIPART_MAX_FILE_SIZE=10MB
export CB_SERVLET_MULTIPART_MAX_REQUEST_SIZE=10MB
export CB_LOG_SK_FILO_RECIPES=debug
export CB_LOG_ORG_SPRINGFRAMEWORK_SECURITY=debug

java -jar target/recipes-1.0.1.jar
