## default connection pool
spring:
    ## PostgreSQL
    datasource:
        hikari:
            connectionTimeout: 20000
            maximumPoolSize: 5
        url: jdbc:postgresql://localhost:5432/recipes
        username: user
        password: User123
    #jpa
    #drop n create table again, good for testing, comment this in production
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                enable_lazy_load_no_trans: true
                event:
                    merge:
                        entity_copy_observer: allow
                jdbc:
                    lob:
                        non_contextual_creation: true
        hibernate:
            ddl-auto: validate

    #flyway                    
    flyway:
    check-location: true              
    #thymeleaf
    thymeleaf:
        cache: false
    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 10MB
#log
logging:
    level:
        sk:
            filo:
                recipes: debug
#        org:
#            hibernate:
#                SQL: debug
#                type:
#                    descriptor:
#                        sql:
#                            BasicBinder: trace
                            
                        
                    

