## default connection pool
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

## PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/recipes
spring.datasource.username=user
spring.datasource.password=User123

#drop n create table again, good for testing, comment this in production
spring.jpa.hibernate.ddl-auto=update

#thymeleaf
spring.thymeleaf.cache=false

#log
logging.level.sk.filo.recipes=debug
